### ISSUE TITLE
Wrong data in repo index.yaml

### ISSUE THREAD

**Issue by TheMeier** [aquasecurity/helm-charts#4]
The repo index lists chart-version 0.4.13 with app-version 0.26.0:

```
  - apiVersion: v2
    appVersion: 0.26.0
    created: "2022-04-25T13:07:38.151030799Z"
    description: Trivy helm chart
    digest: 819a6620554a559eecb43648f628b99332cd57fd2b768ad6d0c051bb635d5b75
    keywords:
    - scanner
    - trivy
    - vulnerability
    name: trivy
    sources:
    - https://github.com/aquasecurity/trivy
    urls:
    - https://github.com/aquasecurity/helm-charts/releases/download/trivy-0.4.13/trivy-0.4.13.tgz
    version: 0.4.13
```

but the app-version in the Chart.yaml is actually 0.25.0.
```
cat trivy/Chart.yaml 
apiVersion: v2
appVersion: 0.25.0
```

I stumbled over this when using https://github.com/fabmation-gmbh/helm-whatup which reported:
```
WARNING: The source repository could not be determined for 'trivy'
```
